title: Marianne Dehasque
logo: /assets/img/2M6A4548-Enhanced-NR-DS-crop.jpeg
email: marianne.dehasque@gmail.com
description: Postdoctoral researcher @ Uppsala university.
favicon: true
remote_theme: vaibhavvikas/jekyll-theme-minimalistic
color-scheme: light

#google_analytics: G-0RXV630V8X

url: "mariannedehasque.github.io/"

plugins:
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme
  - jekyll-sitemap

platforms:
  - name: Research
    icon: <i class="fa-solid fa-file-code"></i>
    link: ./research
  - name: Media
    icon: <i class="fa-solid fa-globe"></i>
    link: ./media
  - name: Résumé
    icon: <i class="fa-solid fa-file-lines"></i>
    link: ./assets/files/MarianneDehasqueResume.pdf
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/mariannedehasque
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/marianne-dehasque/
  - name: Google Scholar
    icon: <i class="fa-brands fa-google-scholar"></i>
    link: https://scholar.google.be/citations?user=Jai0Uj0AAAAJ&hl=en
#  - name: Certifications
 #   icon: <i class="fa-solid fa-award"></i>
  #  link: ./certifications
 # - name: Open Source
  #  icon: <i class="fa-solid fa-ghost"></i>
  #  link: ./open-source
